name: stocks_tutorial
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  dio: ^4.0.4
  flutter_bloc: ^8.0.0
  flutter_config: ^2.0.0
  intl: ^0.17.0
  loading_indicator: ^3.0.2
  syncfusion_flutter_charts: ^19.4.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.3
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
